# Generated by Django 5.1.4 on 2024-12-24 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=200)),
                ('airline_model', models.CharField(max_length=50)),
                ('flight_origin', models.CharField(max_length=100)),
                ('flight_destination', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 12, 24, 17, 20, 34, 694173))),
            ],
        ),
    ]
