# Generated by Django 5.1.4 on 2024-12-25 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_airlines_created_at_booked_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked_list',
            old_name='Airlines_id',
            new_name='Airlines',
        ),
        migrations.AlterField(
            model_name='airlines',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 13, 15, 13, 671899)),
        ),
    ]
