# Generated by Django 5.1.4 on 2024-12-25 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_airlines_id_booked_list_airlines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_list',
            name='passenger_age',
        ),
        migrations.RemoveField(
            model_name='booked_list',
            name='passenger_name',
        ),
        migrations.AlterField(
            model_name='airlines',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 13, 29, 53, 820444)),
        ),
    ]
