# Generated by Django 5.1.4 on 2024-12-25 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booked_list_passenger_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlines',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 13, 33, 13, 190514)),
        ),
        migrations.AlterField(
            model_name='booked_list',
            name='book_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 13, 33, 13, 190514)),
        ),
    ]
